name: Fetch JSON and Save to File

on: [push]

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Fetch JSON and Save to File
      run: node fetch-json.js ${{ inputs.url }} ${{ inputs.filename }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    inputs:
      url:
        description: 'URL to fetch JSON from'
        required: true
      filename:
        description: 'Filename to save the fetched JSON'
        required: true
