name: Fetch JSON and Save to File

on:
  push:
    branches:
      - main

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Fetch JSON and Save to File
        run: node fetchJson.ts

      - name: Commit and push changes
        run: |
          git add .
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "Add fetched JSON to file"
          git push
