name: Handle Datadog

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL from datadog'
        required: true

jobs:
  handle-datadog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Typescript
        run: npx tsc

      - name: Execute dist/index.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          APP_KEY: ${{ secrets.APP_KEY }}
          BASE_SERVER_URL: ${{ secrets.BASE_SERVER_URL }}
        run: node dist/index.js "${{ inputs.url }}" "$API_KEY" "$APP_KEY" "$BASE_SERVER_URL"
